version: '3.8'
services:
  mysql-db:
    image: mysql:8.3
    container_name: mysql_salles
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salles_management
      MYSQL_USER: khalid
      MYSQL_PASSWORD: khalid123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
